# Generated by Django 4.0.4 on 2023-01-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True, null=True, to="product.productcategory"
            ),
        ),
    ]
